### ISSUE TITLE
Forcing "Equidistant" diagonal movement

### ISSUE THREAD

**Issue by InnocenteFederico** [manuelVo/foundryvtt-terrain-ruler#25] opened 2022-03-17 22:05 UTC
It seems that this module force the Diagonal Moving Rule to "Equidistant", even when it is set as "Alternating" or "Euclidean".

**Comment by manuelVo** [comment] 2022-03-18 06:11
In which game system are you experiencing this issue?

**Comment by InnocenteFederico** [comment] 2022-03-18 09:56
DnD5e, but I saw that the reasons why Euclidean and Alternating diagonal movement can not be implemented has already been deeply discussed in #14.

**Comment by manuelVo** [comment] 2022-03-18 10:43
Both Alternating and Euclidean should be working as of now

**Comment by manuelVo** [comment] 2022-03-28 07:26
Setting the mode to "Alternating" on DnD5e works fine for me in my test world. What happens if you disable all modules except Terrain Ruler and Enhanced Terrain Layer. Does that make "Alternating" work?

**Comment by manuelVo** [comment] 2022-03-28 07:27
Setting the mode to "Alternating" on DnD5e works fine for me in my test world. What happens if you disable all modules except Terrain Ruler and Enhanced Terrain Layer. Does that make "Alternating" work?

**Comment by adamAbram** [comment] 2022-04-18 22:54
I'm using the PTU system, and it doesn't have options for how to show distance; it's automatically alternating, but terrain ruler doesn't account for them.

**Comment by manuelVo** [comment] 2022-04-19 07:13
@adamAbram this is unrelated to the issue at hand. Terrain Ruler doesn't know the PTU Game System, which is why it falls back to the default (which is equidistance). Support for the game system can be added quite simply by adding a few lines to `getMeasurementRules` in the `systems.js`: https://github.com/manuelVo/foundryvtt-terrain-ruler/blob/5ca16402fcf00cb6d77bfec3d8bce8abd02f7c26/src/systems.js#L14-L24

**Comment by adamAbram** [comment] 2022-04-19 15:10
> switch (game.system.id) {

I see, thank you.

**Comment by manuelVo** [comment] 2022-11-21 09:05
No further responses from original author. Since I cannot reproduce this in my test world I'll close this ticket.

**Closed by manuelVo** 2022-11-21 09:05 UTC
Labels: bug
